# Generated by Django 5.1.4 on 2024-12-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_one', models.CharField(default='Yes', max_length=255, null=True)),
                ('option_two', models.CharField(default='No', max_length=255, null=True)),
                ('votes', models.IntegerField(default=0, null=True)),
                ('Proposal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.proposal')),
            ],
        ),
    ]
