# Generated by Django 5.1.4 on 2024-12-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='option_three',
            field=models.CharField(default='Not an valid Proposal', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='Proposal',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.proposal'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='option_one',
            field=models.CharField(default='Good Proposal', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='option_two',
            field=models.CharField(default='Bad Proposal', max_length=255, null=True),
        ),
    ]
