# Generated by Django 5.1.4 on 2024-12-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_proposal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='Proposal',
            new_name='proposal',
        ),
    ]
