# Generated by Django 5.1.4 on 2024-12-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_proposal_choice_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='option_one',
            field=models.CharField(default='Good Proposal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='option_three',
            field=models.CharField(default='Not an valid Proposal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='option_two',
            field=models.CharField(default='Bad Proposal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
