# Generated by Django 5.1.4 on 2024-12-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_proposal_option_one_proposal_option_three_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='votes',
            new_name='option_one_votes',
        ),
        migrations.AddField(
            model_name='proposal',
            name='option_three_votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='option_two_votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
